---

- import_tasks: build/preconfigure-k3s.yml

- import_tasks: teardown/drain-and-remove-nodes.yml

- import_tasks: teardown/uninstall-k3s.yml

- import_tasks: validate/state/uninstalled.yml
  when: not k3s_skip_validation
